import assert from "node:assert/strict";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, it } from "node:test";
import { isGeneratedSource, scanPaths, scanText } from "./scan.mjs";

const temporaryDirectories = [];

afterEach(async () => {
  await Promise.all(
    temporaryDirectories.splice(0).map((directory) =>
      rm(directory, { recursive: true, force: true })
    ),
  );
});

describe("anti-slop heuristic scanner", () => {
  it("reports supported high-confidence patterns", () => {
    const findings = scanText([
      "type Json = unknown;",
      "function parse(value: unknown): unknown {",
      "  return value as unknown as Result;",
      "}",
      "vi.mock('./client.ts');",
      "const names = values.filter(Boolean).map(String);",
    ].join("\n"), "src/example.ts");

    assert.deepEqual(
      [...new Set(findings.map((finding) => finding.pattern))].sort(),
      [
        "chained-assertion",
        "filter-map-chain",
        "module-mocking",
        "unknown-parameter",
        "unknown-return",
        "unknown-type-alias",
      ],
    );
  });

  it("recognizes generated headers", () => {
    assert.equal(isGeneratedSource("// @generated\nexport const value = 1;"), true);
    assert.equal(isGeneratedSource("export const value = 1;"), false);
  });

  it("skips generated and conventional output directories", async () => {
    const directory = await mkdtemp(path.join(os.tmpdir(), "anti-slop-scan-"));
    temporaryDirectories.push(directory);

    await mkdir(path.join(directory, "src"), { recursive: true });
    await mkdir(path.join(directory, "dist"), { recursive: true });
    await mkdir(path.join(directory, "public", "assets"), { recursive: true });
    await writeFile(
      path.join(directory, "src", "index.ts"),
      "function parse(value: unknown) { return value; }\n",
    );
    await writeFile(
      path.join(directory, "src", "generated.ts"),
      "// This file is automatically generated. Do not edit.\ntype Json = unknown;\n",
    );
    await writeFile(
      path.join(directory, "dist", "bundle.js"),
      "type Json = unknown;\n",
    );
    await writeFile(
      path.join(directory, "public", "assets", "bundle.js"),
      "type Json = unknown;\n",
    );

    const result = await scanPaths(["."], { cwd: directory });

    assert.equal(result.filesScanned, 1);
    assert.equal(result.generatedFilesSkipped, 1);
    assert.equal(result.findings.length, 1);
    assert.equal(result.findings[0]?.pattern, "unknown-parameter");
    assert.equal(result.findings[0]?.file, "src/index.ts");
  });

  it("supports additional ignored directory names and paths", async () => {
    const directory = await mkdtemp(path.join(os.tmpdir(), "anti-slop-ignore-"));
    temporaryDirectories.push(directory);

    await mkdir(path.join(directory, "lib"), { recursive: true });
    await mkdir(path.join(directory, "packages", "demo", "generated"), { recursive: true });
    await writeFile(
      path.join(directory, "lib", "authored.ts"),
      "function parse(value: unknown) { return value; }\n",
    );
    await writeFile(
      path.join(directory, "packages", "demo", "generated", "client.ts"),
      "type Json = unknown;\n",
    );

    const defaultResult = await scanPaths(["."], { cwd: directory });

    const ignoredResult = await scanPaths(["."], {
      cwd: directory,
      ignore: ["lib", "packages/demo/generated"],
    });

    assert.equal(defaultResult.findings.length, 2);
    assert.equal(ignoredResult.findings.length, 0);
  });
});
